Added the SLIIT FOSS Community Page
sliit-foss/Campus-Club pull request #1
Opened 2021-09-20 06:51 UTC by SahasR

Sourced from existing assets page.

2021-09-20 06:51 UTC, SahasR commented
@Shehanka requesting reviewal please.

2021-10-06 00:31 UTC, Shehanka requested changes

2021-10-06 00:31 UTC, Shehanka commented on cc/SLIIT_FOSS_Community.md
> +Absolutely nothing! Everyone starts from somewhere so its extremely fair to have people from diverse backgrounds. What matters to us is a willingness to learn and the ability to put time in!
Don't change the original template points

2021-10-09 04:38 UTC, Sewvandiii requested changes
@SahasR Keep the original template points

2024-04-13 08:59 UTC, closed without merging